[package]
name = "dm2120f22"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
<<<<<<< HEAD
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "35f0f1ba7176254c4474e4358f4d0044832b9698"}
=======
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "c8760bde60264742b5c4e51e2d721f2290d735f4"}
>>>>>>> 8ca5c69676096953a7a05158052cfbfd61d0142d
